[build-system]
requires = [ #какие пакеты должны быть установлены, чтоб процесс мог работать
  "build_with_cython >= 0.0.3"
]

build-backend = "build_with_cython.backend" #пакет, непосредственно выполняющий сборку